In [15]:
##################
##### Numpy
##################
import numpy as np
a = np.array([0,1,2,3])
print(a)

[0 1 2 3]


In [2]:
my_array = np.array([
                    [[1,2,3],[4,5,6],[7,8,9]],
                    [[3,2,1],[6,5,4],[9,8,7]],
                    [[1,2,7],[4,5,7],[1,2,7]]
                    ])
# 3 dimensions


In [3]:
print(my_array[0,2,:]) 
# the zero-th index of the first dimension gives the first matrics


[7 8 9]


In [4]:
import numpy as np
my_array = np.array([1,'a_string'])
print(my_array)
# automaticlly convert integer to string --> Homegeneous

['1' 'a_string']


In [12]:
l = list(range(10))
print(l)
[i ** 2 for i in l]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [22]:
L = list(range(10))
%timeit [i**2 for i in L]

3.45 µs ± 90.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [16]:
a = np.arange(1000)
%timeit a**2 # much faster when using numpy

1.11 µs ± 11.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [24]:
b = np.arange(10)
print(b)
b**2

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [29]:
# Navigating NumPy Documentation
np.lookfor('create array')

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or a ctypes POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.ma.mvoid.__new__
    Create a new masked array from scratch.
numpy.lib.format.open_memmap
    Open a .npy file as a memory-mapped array.
numpy.ma.MaskedArr

In [37]:
# Creating Arrays
a = np.array([0,1,2,3])
print(a)
print(a.ndim) # number of dimensions
print(a.shape) # number of elements in each dimension
print(len(a))

[0 1 2 3]
1
(4,)
4


In [43]:
b = np.array([[0,1,2],[3,4,5]])
print(b)
print(b.ndim)
print(b.shape)
print(len(b))

[[0 1 2]
 [3 4 5]]
2
(2, 3)
2


In [46]:
c = np.array([[[0],[1]],[[2],[3]]])
print(c.shape)

(2, 2, 1)


In [50]:
# functions for creating arrays -- similar to python range function
a = np.arange(10)
b = np.arange(1,9,2)
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7]


In [54]:
c = np.linspace(0,1,6) # start, end, num-points
d = np.linspace(0,1,5,endpoint=False)
print(c)
print(d)

[ 0.   0.2  0.4  0.6  0.8  1. ]
[ 0.   0.2  0.4  0.6  0.8]


In [67]:
a = np.ones((3,3,3)) # reminder: (3,3) is a tuple
b = np.zeros((2,3,2))
print(a)
print(b)


[[[ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]]
[[[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [77]:
c = np.eye(4)
print(c)
d = np.diag(np.array([1,2,3,4]))
print(d)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [87]:
# Generating Arrays if Random Numbers
a1 = np.random.random((3,3)) # uniform in [0,1]
print(a1)

a2 = np.random.rand(4,4)  # uniform in [0,1]
print(a2)

b = np.random.randn(4)  # gaussian
print(b)

c = np.random.seed(1234) # setting the random seed

[[ 0.19151945  0.62210877  0.43772774]
 [ 0.78535858  0.77997581  0.27259261]
 [ 0.27646426  0.80187218  0.95813935]]
[[ 0.87593263  0.35781727  0.50099513  0.68346294]
 [ 0.71270203  0.37025075  0.56119619  0.50308317]
 [ 0.01376845  0.77282662  0.88264119  0.36488598]
 [ 0.61539618  0.07538124  0.36882401  0.9331401 ]]
[-1.12650247  1.65887284 -0.66044141  1.04108597]
None


In [89]:
# basic data type
a = np.array([1,2,3])
print(a.dtype)

int64


In [90]:
a = np.array([1.0,2.0,3.0])
print(a.dtype)

float64


In [96]:
c = np.array([1,2,3],dtype=float)
print(c.dtype)
d = np.array([1,2,3],dtype=np.float16)
print(d.dtype)

float64
float16


In [105]:
# the default data type is floating point:
a = np.ones((3,3))
print(a.dtype)

# there are also other data types: complex
d = np.array([1+2j,3+4j])
print(d.dtype)

# there are also other data types: bool
e = np.array([True,False,True])
print(e.dtype)

# there are also other data types: string
f = np.array(['hello','你好'])
print(f.dtype)

float64
complex128
bool
<U5


In [111]:
# basic visualization -- matplotlib
import matplotlib.pyplot as plt
%matplotlib inline 
#display imagine inside of notebook
%config InlineBackend.figure_format = 'svg' #display imagine using format 'svg'

In [116]:
# plt.plot([1.0,2.0,3.0],[0.0,0.2,0.6])

In [117]:
# x = np.linspace(0,3,20)
# y = np.linspace(0,9,20)
# plt.plot(x,y)
# plt.plot(x,y,'o')

In [2]:
# indexing array

import numpy as np


In [3]:
a = np.arange(10)
print(a)
a[0],a[-1]

[0 1 2 3 4 5 6 7 8 9]


(0, 9)

In [4]:
# the usual python idiom for reversing a sequence is supported:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [19]:
# for multidimensional arrays, indexes are tuples of integers:
a = np.diag(np.arange(3))
print(a)
print(a[1,1])
a[2,1] = 8
print(a)

[[0 0 0]
 [0 1 0]
 [0 0 2]]
1
[[0 0 0]
 [0 1 0]
 [0 8 2]]


In [21]:
b = np.diag(10+np.arange(3))
print(b)

[[10  0  0]
 [ 0 11  0]
 [ 0  0 12]]


In [22]:
###################
# slicing the array
###################
a = np.arange(10)
a[2:9:3] # start, end, step

array([2, 5, 8])

In [23]:
a[:4] # note the last element is not included

array([0, 1, 2, 3])

In [25]:
# combine assignment and slicing
a = np.arange(10)
a[5:] = 10
print(a)

[ 0  1  2  3  4 10 10 10 10 10]


In [28]:
b = np.arange(5)
a[5:] = b[::-1]
print(a)

[0 1 2 3 4 4 3 2 1 0]


In [33]:
###################
# view of an array
###################
a = np.arange(10)
print("a:",a)
b = a[::2]
print("b:",b)
np.may_share_memory(a,b) 


a: [0 1 2 3 4 5 6 7 8 9]
b: [0 2 4 6 8]


True

In [34]:
# if a and b may share memory, I change value for a, it will reflect to b as well
b[0] = 99
print(a)

[99  1  2  3  4  5  6  7  8  9]


In [36]:
# force copy
a = np.arange(10)
c = a[::2].copy()
c[0] = 12
print(c)
print(a)

[12  2  4  6  8]
[0 1 2 3 4 5 6 7 8 9]


In [37]:
###################
# fancy indexing
###################

# 1. using boolean maskes
np.random.seed(3)
a = np.random.randint(0,20,15)
print("a:",a)


a: [10  3  8  0 19 10 11  9 10  6  0 12  7 14 17]


In [39]:
mask = (a % 3 == 0)
extract_from_a = a[mask]
extract_from_a

array([ 3,  0,  9,  6,  0, 12])

In [41]:
# very helpful to assign a new value to sub-array
a[a % 3 == 0] = -1
a

array([10, -1,  8, -1, 19, 10, 11, -1, 10, -1, -1, -1,  7, 14, 17])

In [45]:
# 2. indexing with an array of integers
a = np.arange(0,100,10)
print(a)

a[[2,3,2,4,2]] # [2,3,2,4,2] is a python list

[ 0 10 20 30 40 50 60 70 80 90]


array([20, 30, 20, 40, 20])

In [46]:
# assignment
a[[9,7]] = 100
a

array([  0,  10,  20,  30,  40,  50,  60, 100,  80, 100])

In [56]:
a = np.array(10)
idx = np.array([[3,4],[9,7]])
print(idx)
print(idx.shape)
#print(a[idx])


[[3 4]
 [9 7]]
(2, 2)
